### ISSUE TITLE
Remove twitter->mastodon direction

### ISSUE THREAD

**Issue by Gargron** [renatolond/mastodon-twitter-poster#114]
Before I say anything else, I want to preface by saying that I realize my word might have a lot of power due to my position and this is absolutely not an attempt to exercise that power, order or force anyone into anything.

I want you to consider removing the twitter->mastodon cross-posting direction as I believe it is harmful to the fediverse. Here are a couple reasons why:

- It gives people an excuse to ignore Mastodon. Sign up, set up cross-poster, leave. They won't see the community, they won't experience Mastodon's features, they'll remain Twitter users. No use for us.
- Nobody will switch to Mastodon just to see content they would see on Twitter in its original form
- It's anti-promotional. Cross-posting is a way to promote the platform where the content originates. That's why tumblr and facebook cross-post to Twitter while linking to the original. By having so much Twitter content on Mastodon, we are promoting Twitter.

I think that having only the mastodon->twitter direction should be sufficient for all legitimate uses. Mastodon has superiour posting capabilities.

The only problem is of course it's harder to take something away once you've given it.

**Comment by renatolond** [comment]
Hi, @Gargron!

I understand your concerns, but I do not agree with them. First because there were crossposters before and even if I stop supporting this direction, other services will allow the same (i.e. right now, twidere allows crossposting, https://github.com/foozmeat/moa too, and some accounts were using t2m or other similar scripts for that end).

Your concern about users that set-up the crossposter and leave is mitigated by rules around crossposting on the instances, at least for smaller instances. For bigger instances I think something like the idea by @ThisMissEm is what I would go for. Some kind of .well-known configuration in which the admin of the instance can define rules for the crossposter (if it's allowed at all, if RTs should be allowed, and so on).

> Nobody will switch to Mastodon just to see content they would see on Twitter in its original form
I agree, at the same time, some users won't leave twitter at all. I have several close friends that wouldn't trade twitter for Mastodon because of the lack of community. However, some of them are using both because they crosspost to mastodon and they still get answers and interactions in Mastodon too.

> I think that having only the mastodon->twitter direction should be sufficient for all legitimate uses. 
This is a very limited use case. Several 3rd-parties only allow posting to twitter and facebook, what comes to my mind immediately is Nintendo Switch, which is why a lot of people wanted Twitter -> Mastodon posting to begin with.

I also think that having a few code-bases that do crossposting allows us to control better how crossposting is done in the end. If everyone does their own crossposting scripts, each will have their own format and makes filtering harder. Assuming we have a good way of filtering in Mastodon, a user could filter everything coming from the crossposter app, for instance.

**Comment by Gargron** [comment]
You've mentioned a real use case with Nintendo -> Twitter -> Mastodon, and there probably more like it. So instead of removing the direction altogether, how about reducing the amount of stuff people can cross-post, by which I mean: If it mentions someone from Twitter, don't cross-post, exclude quote-tweets and retweets.

Even forks that autolink Twitter usernames unlike upstream can't do it well, because it breaks UX expectations of how mentions look and what happens when you click them. There's just no way that looks good to anyone.

**Comment by mkody** [comment]
Seeing a `@username@host.tld` is something that shows up too when crossposting the other way (well, there's now an option for that) and it's better that way so we can get the context to who we are speaking to.
Adding an option to "not crosspost if someone is mentioned" could be a good idea and that's pretty much all we can expect from this issue so far.

Removing features will only anger people (and forks will be made). There are crossposters who only do one way, and this one can do both while still giving a lot of options.
You talked about quote-tweets and retweets but those can be turned off, which I did for retweets (but still allow quotes since I'm getting more control over it and can add a CW).

Also, to reply to
> Nobody will switch to Mastodon just to see content they would see on Twitter in its original form

Mastodon has great moderation tools, user can mute/block those accounts or just not follow them. Heck the crossposter can even add a CW to every tweets. And I'm really glad I can still follow people even if they're not using Mastodon anymore, it's better than having a dead account and loosing track of what's happening (and when interacting with them maybe they'll get a mail and then login, who knows!).

That's my 2 cents. For me Renato made the best crossposter that has enough options so it doesn't bother so many instances who might have stricter rules.

**Comment by Gargron** [comment]
>Seeing a @username@host.tld is something that shows up too when crossposting the other way

I don't care about what happens on Twitter's side.

>You talked about quote-tweets and retweets but those can be turned off

I suggest removing the option to ever turn them on. I had someone who turned everything on and his account was spammed with RTs. When I showed him what his account looked like he immediately turned that feature off.

>Mastodon has great moderation tools, user can mute/block those accounts or just not follow them

The problem is in the public timelines getting spammed with this, requiring every single user to add a filter or mute/block lots of accounts. The cross-poster is down now due to Twitter's API limitations and everyone I know is sighing relief over on Mastodon. I can go and hardcode a filter for the `@twitter.com` substring into Mastodon itself, but that's a harsh measure and I'd rather enquire at the source first (here). Make cross-posted stuff unlisted at most then.

If admins were to block the cross-poster app, the mastodon->twitter direction would be lost too, which is not ideal.

>it's better than having a dead account

For admins, such dead-but-posting accounts are not free, they still consume database/media storage. For the community, they are mostly an exercise for the mute/block button and an annoyance.

>If they don't stick to Mastodon, there's probably a reason. You can't force users to stay and removing all crossposter will not fix it (might even do worse).

As I said, not having an option to crosspost can actually motivate people to give it a legitimate attempt; you can't underestimate people's lazyness. But even if not, that's fine. The problem is the negative effect such dead-but-posting accounts have on people who actually use Mastodon.

**Comment by renatolond** [comment]
> The problem is in the public timelines getting spammed with this, requiring every single user to add a filter or mute/block lots of accounts.

Again, the solution for this is to restrict when users can crosspost to public timelines. I said before, I'm up for working with instance admins to make their lives easier to respect the rules they impose on their instances. But I'm not going to remove entirely RTs and quotes or the public posting of them, not all instances are the same and not everyone is bothered by having Twitter content on the fediverse.

I have worked to reduce the bother of incoming twitter content: the blanket cws, removing link only RTs which left no choice but to check twitter for the content, adjusting default options to post stuff unlisted. I'm still up to working on that sense.

**Comment by Cassolotl** [comment]
If I set up the crossposter to only post from Mastodon to Twitter, that would annoy all my Twitter followers a lot more than the other way around. (And I have twice as many followers on Twitter so it's even more annoyance, statistically!) That's because Mastodon allows more characters, so my Twitter account would get a lot more "click here to read the rest", which is awful. It's fine in the other direction, because Mastodon allows more characters than Twitter.

Also I post about more meta stuff on Mastodon, which would be weird and out of place on Twitter.

Image descriptions do crosspost, which is excellent, and if I'm posting images I prefer to post them on Twitter and have them crossposted over (rather than the other way around), because the Twitter UI for image descriptions is much better than the Mastodon UI for image descriptions.

My tweets that get crossposted to Mastodon rarely have @-mentions in them, and it's unusual for them to have anything in them that indicates that they're crossposts from Twitter at all.

So, obviously my situation isn't universal but I'd be pretty annoyed if crossposters stopped doing *Twitter --> Mastodon*. If that happened I would probably use Mastodon a LOT less, because fewer posts to Mastodon means fewer replies and interactions, etc.

**Comment by Gargron** [comment]
You seem to be more concerned with what's good for Twitter even at the expense of what's good for Mastodon, and I obviously disagree with that.

**Comment by Cassolotl** [comment]
Not what's good for Twitter - what's good for my friends.

**Comment by remram44** [comment]
Another important problem is that Twitter keeps blocking the crossposter in the Mastodon->Twitter direction. If you want to post original content and have it go to both, at the moment you have no choice but to post on Twitter.

This doesn't indicate a preference for Twitter as a network nor as an interface but is just how it is. Not everything I do on Mastodon has the promotion of Mastodon in mind.

**Comment by Gargron** [comment]
>Another important problem is that Twitter keeps blocking the crossposter in the Mastodon->Twitter direction

Twitter is smart in this, for the exact reasons I have outlined in my original post.

**Comment by ardydo** [comment]
Honestly I'm just baffled just how out of touch this suggestion is. What does it even achieve? What crossposting from Tw -> Masto would ever be deactivated, what would stop people from developing other crossposter that will do it? What would stop people from just switching to other one that already does? Or even just jump a few commits back and fork this one? The only thing it would do is cripple Lond's project.

Someday you're annoyed that people are using hammers to smash things and that's bad, so what do you do? You educate people to not smash things? No, you write a letter to the hammer factor asking for then to stop making them. What about homemade hammers? What about that giant stick I just found around? What about this hydraulic press? Don't mind them. Just ban hammer and we'll be good. You're annoyed at people behavior and the content they are making, just like you said yourself in this issue. It does not have nothing to do with the tool and it will keep happening regardless of the tool if people don't change.

**Comment by remram44** [comment]
> Twitter is smart in this

Twitter is smart in protecting their user base and the interest of the for-profit company, brand, and shareholder reports. Twitter is smart in the way they lock users in the isolated silo they set to create.

I am not saying we shouldn't be smart, but is that the sort of goal the Mastodon project has as well?

**Comment by Gargron** [comment]
>What does it even achieve? What crossposting from Tw -> Masto would ever be deactivated, what would stop people from developing other crossposter that will do it? What would stop people from just switching to other one that already does? Or even just jump a few commits back and fork this one?

OK so because *someone* might do [bad thing], there's *no point* in not letting [bad thing] happen in the most popular, go-to project? Cool.

>Twitter is smart in protecting their user base and the interest of the for-profit company, brand, and shareholder reports. Twitter is smart in the way they lock users in the isolated silo they set to create.

Nothing of this has anything to do with locking anyone into anything, and everything to do with promotion. Either you're promoting Twitter to Mastodon users, or you're promoting Mastodon to Twitter users. I don't think we should be promoting Twitter, because that's their job, not ours.

You don't see Tumblr letting people cross-post tweets into their blogs (I'm not talking about HTML widgets anyone can put on their site), but you see Tumblr posts cross-posted to Twitter. It's very basic.

**Comment by Cassolotl** [comment]
I think it should also be mentioned that there's some bias going on here because we only ever notice the bad crossposting on Mastodon. When people use crossposters well, you wouldn't know that they're crossposting unless you go digging.

![screen_shot_2018-08-26_at_16_49_40](https://user-images.githubusercontent.com/6607512/44630062-01f34c80-a950-11e8-8681-16cb383e2cdf.png)

Lots of people use crossposters to maintain an active presence in both places. If you cut off crossposters from Twitter to Mastodon we'll miss out on some great posters. I follow (in both places) several people who crosspost from Twitter to Mastodon.

This whole thing where people are treating Twitter and Mastodon like bitter enemies seems so counterintuitive to me. Sure the people in charge of Twitter are awful, but we're not exactly "promoting" Twitter by letting people crosspost. We're giving people a way into Mastodon, a way to be in both places. I follow people on Tumblr who crosspost from Wordpress to Tumblr and that's a good thing! It gives us more ways to connect and share with each other. But when a company does something petty that cuts people off from other people, they quite rightly get bitched about - like when WhatsApp was threatened by the existence of Telegram, and so it made Telegram URLs unclickable in WhatsApp, but left all other URLs working. It was petty and it made them look bad.

**Comment by lightweight** [comment]
Sorry, I fully support Eugen on this call. The issue is that Twitter is a bad actor in all this. Yes, they've got the network effect on their side, but they're not working in the interest of their users, they're working in the interest of their shareholders. We should *all* be aiming to be *open first*. Then, if you're open, you can take advantage of the network effect second (by auto-posting from open -> closed) without selling out your values. Going the other way just perpetuates Twitters undesirable dominance. We folks who understand this stuff have the power to change the (currently badly broken) status quo by sticking to our values.

**Comment by remram44** [comment]
Sticking to your values is very laudable, however forcing them on your users just makes you a bad actor too.

You could put a warning up, telling users to consider not using the feature because of its effects on the network's experience, however removing a feature we are using because you feel it's "the wrong way" or detrimental to your product or brand just isn't in the spirit of openness at all.

**Comment by lightweight** [comment]
Ok, that's a fair point. I would then suggest a note in the user interface where a user selects which forwarding services to enable, explaining this value consideration (particularly in light of the fact that the originator of one half of the equation, Mastodon, has made that clear request). I'll look into pulling together a dev environment so I can provide a PR (although if someone beats me to it, even better :) ).

**Comment by mkody** [comment]
> how many instances are currently running? Any idea? Are all of them blocked from posting on Twitter?

I have mine working with 7 accounts and it didn't get blocked (yet). It went through validation too with "Crossposter" in the name and a correct description.

**Comment by renatolond** [comment]
> Are all of them blocked from posting on Twitter? Is it a voluntary cease and desist or official (on Twitter's part)?

No. The crossposter allowed mention to be crossposted, which is against Twitter automation rules. I fixed it, but because of a bug, some mentions still passed over. Because of the size of the crossposter, it got caught by some automated filter and the writing direction was restricted. It is related to the my api key, not some decision on Twitter's side, other crossposters and other instances of this crossposter still are allowed to post regularly, as far as I know.

**Comment by renatolond** [comment]
You're all welcome to open other issues to improve on how to decrease the noise of the crossposter over at Mastodon, I opened some issues like #124, and there's also #127 to limit toots/tweets with @-mentions.

As for this one, I don't plan on shutting down this direction. Thanks for the input!
