### ISSUE TITLE
Remove the elephant emoji when posting mastodon usernames/urls

### ISSUE THREAD

**Issue by j-afarian** [renatolond/mastodon-twitter-poster#131]
Currently, if you tag a Mastodon user in your toot, it's prepended with an elephant emoji on the Twitter end, example:

**`🐘username@mstdn.io`**

It can be really confusing to have an elephant emoji show up in the middle of a sentence without any context. A lot of Twitter users don't even know what Mastodon is, and wouldn't recognize the Elephant as being symbolic of the platform, it just makes the Tweet confusing.

Also, this doesn't seem to occur in reverse? Twitter usernames aren't prepended with a bird when they're crossposted to Mastodon, they just show up as **`@username@twitter.com`** or similar.

I'd like to suggest removing the addition of this emoji on the Twitter side, as it doesn't add any value; in fact, I've been told it's confusing when trying to read my posts :(

**Comment by renatolond** [comment]
Hi, I can remove the emoji, but then it would look like an email, so I don't know if it would be much better :T

It used to post as `@username@mstdn.io` but twitter started restricting the crossposter because their spam detection would detect it as a twitter mention, which is weird, but well.

Would `username@mstdn.io` look better for you?

**Comment by j-afarian** [comment]
Ah, I see - so that's why the leading `@` was removed :l

In that case, I guess the addition of the emoji is probably better than having it look like an email (which, you're right - it does...)
