### ISSUE TITLE
Statuses crossposted from Mastodon to Twitter use full-width asterisks

### ISSUE THREAD

**Issue by unascribed** [renatolond/mastodon-twitter-poster#134]
When I post a status on Mastodon containing the asterisk character (`*`), it gets crossposted to Twitter with all the asterisks replaced with full-width asterisks. (`＊`).

![screenshot](https://user-images.githubusercontent.com/6185037/46693510-7f6dd600-cbf9-11e8-8beb-94bd72d63e7b.png)

![screenshot](https://user-images.githubusercontent.com/6185037/46693526-8ac10180-cbf9-11e8-801d-ce843a617d14.png)

**Comment by renatolond** [comment]
Hi!
This is a workaround around an issue on the library I use for twitter: https://github.com/sferik/twitter/issues/677

I saw that recently a workaround was added, I have to see if I can use it here. I'll try to check when I have some time :)

**Comment by scy** [comment]
There’s been some progress in the issue in the Twitter gem (sferik/twitter#677), [I’ve tried to summarize the issue](https://github.com/sferik/twitter/issues/677#issuecomment-586599827) there.

In particular, there’s [a proposed solution](https://github.com/sferik/twitter/issues/677#issuecomment-586547719) that should be perfectly fine to just copy & paste into this project and get rid of the full-width asterisk workaround.

The reason why I’m so interested in getting this fixed is that I usually toot in German, and in German lots of nouns (e.g. professions) have a male and a female form, like “Bäcker” (male baker) and “Bäckerin” (female baker). That binary system of course sucks for non-binary persons, which is why there are several ways to try to express these words in a more inclusive way, like “Bäcker_in” (leaving a gap for “other” genders).

The most popular way to do that however is “Bäcker*in” with an asterisk (which has less of the negative connotations of non-binary people being a “gap”, for more information see the (German only) Wikipedia article [Gendersternchen](https://de.wikipedia.org/wiki/Gendersternchen)). But now, whenever I try to use that preferred way of inclusive language on Mastodon, it gets crossposted to Twitter with a really ugly looking full-width asterisk (see the screenshot at the top of the issue). It’s not an issue when crossposting the other way around, from Twitter to Mastodon, which is really the only reason why I’m still writing my toots/tweets on Twitter. (And I’d love to make Mastodon my default, but as long as this is not fixed, I really can’t do it.)

Sorry for getting into German linguistics in what’s mainly a technical issue, but maybe @renatolond wasn’t aware of this and may even re-prioritize this issue based on its diversity implications.
