### ISSUE TITLE
Unfederated toots are crossposted to twitter

### ISSUE THREAD

**Issue by aldonogueira** [renatolond/mastodon-twitter-poster#135]
I have just published a toot that was addressed to the people on my instance. It was crossposted to twitter. It doesn't seem appropriate to publish something on twitter that wasn't meant to be published to other instances on the fediverse. I hope it's an easy filter to be done

**Comment by renatolond** [comment]
Yeah, I'm aware, but since local-only statuses are still not official (only in glitch-soc and some forks) I need to double check if there's a way to detect it :)

**Comment by timcowlishaw** [comment]
Hey folks, sorry too bump this four years later, but I also just came across this behaviour and was confused by it - has anything changed around the officialness / easy of detecting local-only statuses since this was opened? I'm new to Activitypub / Mastodon but have plenty of experience with Ruby, and would be happy to attempt a PR to add filtering of local only statuses as an option (or as the default behaviour), if it were of interest!
