### ISSUE TITLE
Replacing Twitter handles in mentions with the respective Mastodon handle

### ISSUE THREAD

**Issue by clerie** [renatolond/mastodon-twitter-poster#160]
If someone posts a message at Twitter and mentions someone, the Twitter handle is used. It would be nice, to replace the Twitter handle with the repective Mastodon handle before crossposting.

The needed information may still exist in the crossposter database or can be provided by the official Mastodon Twitter Bridge.

**Comment by renatolond** [comment]
Hi!
This information is not readily available for the crossposter. My crossposter instance, which I think it's the biggest, has less than 2000 active users, even if I implement something like that, only those < 2k users would be replaced, the majority of the users would still not be replaced.

The mastodon twitter bridge is in no way related to the crossposter and users did not authorize their data to be shared with 3rd parties, so that's not an option.

It would be nice to avoid having twitter handles over in the fediverse, but unfortunately it's not technically possible.

**Comment by clerie** [comment]
There is still an issue for this https://source.joinmastodon.org/mastodon/bridge/issues/5
I can try to talk to someone responsible for this, to get something rolling.

**Comment by renatolond** [comment]
I don't think the bridge even works at this moment: https://mastodon.social/@Gargron/101427356253182095
Which means there's no way for me to get that information reliably, even if the bridge started giving 3rd party access.

**Comment by clerie** [comment]
Oh, thats a bad news. But I think, there is another solution:

Mastodon supports verified Homepages by using the rel="me" HTML tag. The crossposter can use this, checking, if on the verified homepage is a link to a (rel="me") verified Twitter account and just use this. It may be a bit resource intensive, but is a stable and federated solution.

**Comment by NiklasMM** [comment]
Could this be implemented in a manual way? For example users could be given the possibility to define a number of Mastodon/Twitter account pairs, which the crossposter would then automatically resolve. For all other accounts the current behaviour remains.

This would not solve the problem completely, but at least give user the opportunity to resolve it with accounts they tag often.

**Comment by renatolond** [comment]
@NiklasMM that sounds like a good idea :)
I'll check into it :)
(sorry for taking so long to answer, been a bit busy IRL)

**Comment by clerie** [comment]
Ohh, thats nice 👍
@NiklasMM's idea may be extended with my idea, described above, later. So nobody have to fill in the values manually and the data can get retrieved by any software.

**Comment by GidiKroon** [comment]
And if the Mastodon handle does not exist or is not known, a hyperlink to the Twitter profile page can be inserted around the @ -mention. I don't know how, but I've seen hyperlinks work in Mastodon, you just can't enter them in the UI (but you could in Pleroma, though it's currently broken).

**Comment by p0sty** [comment]
I came here to suggest exactly this - I just want to underline that this would be a major feature enhancement. There are plenty of good reasons to move to Mastodon, but I think a key one for twitter posters is that their feedback is not respected because they are the product, not the ultimate end users (marketers and ads). 

I think this project has both the potential to inspire people to move to mastodon, or for twitter themselves to improve.

Both outcomes would be great - I've explained more in my #DepreciateTwitter post here:
https://twitter.com/posty/status/1141818476572499968

**Comment by ctr49** [comment]
There is [Debirdify](https://pruvisto.org/debirdify/) and [Fedifinder](https://fedifinder.glitch.me/) now, so it should be possible to use either one (or their logic) to identify Mastodon users and replace Twitter handles with the Mastodon handle.
