### ISSUE TITLE
Dont spam the timeline with "twitter.com"

### ISSUE THREAD

**Issue by Nutomic** [renatolond/mastodon-twitter-poster#217]
Recently I am seeing more and more and more posts like this on my Mastodon timeline, and I'm told they are coming from your bot. Frankly its ridiculous that I'm seeing 3 (or more) mentions of "twitter.com" in a single toot. I didnt sign up on Mastodon to follow people on Twitter. 

![64ee5891f70cc312](https://user-images.githubusercontent.com/1044450/63382475-532ef400-c38a-11e9-9e07-5d1d2d2a1647.png)

I suggest that you hide the `@twitter.com` part of usernames, because Mastodon doesnt display the instance part of the username either.

**Comment by realityfabric** [comment]
What happens if the person posting with the bot is on the same instance as another person with the same @ handle? It is really obnoxious to have to see the domain tacked on all over the place, but is there a way to prevent it from sending notifications to people who happen to share handles on different domains?

**Comment by Nutomic** [comment]
Maybe just post the username without @ then?

**Comment by realityfabric** [comment]
that would definitely prevent it from tagging local users, yeah

**Comment by renatolond** [comment]
Hi!
Posting retweets or quotes is an option that can be turned off by the users of the crossposter.

Some other users use `@twitter.com` and other markers as ways to silence retweets and general Twitter mentions, removing it would break those silences.
Also, some instances transform those mention-like into links.

I don't plan to remove them because of those reasons, there is an open issue at Mastodon to support muting clients, which I think would solve the issue for you : https://github.com/tootsuite/mastodon/issues/8271
