### ISSUE TITLE
replys to other users tweets not showing up when posting from twitter to mastodon

### ISSUE THREAD

**Issue by Goldmaster** [renatolond/mastodon-twitter-poster#440]
Hi there, not sure if this can be fixed, but I'm using the web-based design which is very nice and simple to set up and I'm wondering why replies to other users tweets on Twitter are not showing up in mastodon? could end up sort of looking like this on mastodon.

`@twitterusername whatever I was asking about https://t.co/BdUBkoYXng `

any chance of an update, please?

**Comment by renatolond** [comment]
Hi!
This is by design, it showw no replies over Mastodon because you'd have no context (the tweets from other users are not crossposted, so you'd have a post without context over at mastodon with a twitter user handle). I have no intention of supporting replies to other users at this time, but thanks for getting in touch!
