### ISSUE TITLE
Disable crosspost of CW'ed posts

### ISSUE THREAD

**Issue by ghost** [renatolond/mastodon-twitter-poster#47]
Currently, I'm on a private instance with me, myself, and I. If I post a private post with a content warning, anyone without an account on my instance following me (aka anyone who isn't me) cannot get anything from the link to that post but an error. Even if they have an account on another instance following me, pasting post URLs in the search bar to load them does not work for private posts.

Could an option to simply not post CWed posts to Twitter, or post them in a format such as
`CW [text]// [post] ` or anything be added?

**Comment by renatolond** [comment]
Both options could be added, both the text and also not posting. However, for private posts in general, if you go above twitter max twitter characters, it would be cropped and in the end you would not get the full length text anyway. The same would happen if you post an image with the sensitive tag, because if I remember right, the image does not get crossposted and a link is generated instead.

In other words, crossposting private posts can lead to not being able to see the post unless you're on Mastodon and following the given person.

Regarding the link not working, maybe that's something to open an issue on Mastodon's side, given that you're following a given person and you have a link to a private post they posted, maybe you should be able to find the post back with the link

In any case, I'll try to add an option to not crossposted CW'd posts.

**Comment by Fidgetcetera** [comment]
Thank you! And on a side note, nah, I've reached out about the private post issue before. It's apparently intentional to just not be able to load private posts with that method ever, from what I heard.

**Comment by bluebirch** [comment]
Is this in the pipeline? I would very much like to avoid crossposting of CW:ed toots.

**Comment by renatolond** [comment]
Hey!
Haven't had much time to work on the crossposter lately. But this is in the pipeline, together with #33 :)
