### ISSUE TITLE
It's possible to have a tweet passing the 500 chars if it has enough mentions

### ISSUE THREAD

**Issue by renatolond** [renatolond/mastodon-twitter-poster#54]
If the tweet is a retweet of a tweet with a lot of mentions, it can surpass the 500 chars and will fail being posted to mastodon. I have no idea what would be the proper treatment in this case, but at least it should not get stuck trying to post it.

**Comment by trwnh** [comment]
Idea: Collapse mentions into "mentioned you and n others".

Most of the time, the context of a mention only relies on the first person mentioned, and very rarely on the first few people. Reply boats on Twitter get very large easily, and unrelated people are stuck in the tagged users list. Since Mastodon has 500 characters and Twitter has only 280, it should be easier to handle the Twitter -> Masto conversion than the Masto -> Twitter conversion. Posting a link to the original status is also an option, but should not strictly be necessary.

**Comment by renatolond** [comment]
I've decided to just ignore those tweets for now. Indeed a good option would be to add the "mentioned you and n others", but right now those tweets get the whole profile stuck and I have to manually skip them, so I chose to ignore them for now and later prioritize an option to change the reply to something like that
