### ISSUE TITLE
Feature request: post RT and quotes ONLY as link

### ISSUE THREAD

**Issue by Simone98RC** [renatolond/mastodon-twitter-poster#602]
Hello,
often happens that RT and quotes **are divided into two toots** because of characters limit: this behavior is confusing and **could be considered as spam** or eccessive activity by admins of little Mastodon communities.

Actually the only options are "as old RT" and "as old RT and link".
So, I strongly suggest the option "as old link" for both quotes and retweets options (maybe it's also needed as choice for reply option).
By enabling this option, the toot should be:

_RT @renatolonddev@twitter.com: https://twitter.com/renatolonddev/status/904738384861700096_

Thanks in advance!

**Comment by renatolond** [comment]
Hi, @Simone98RC, I think this would be even more spammy, since users would have only a collection of links if you looked at their profile.
The links are there only for a "credit" kind of thing (to be able to find the original tweet if a user wants to) and I'm not too keen on making them the only option (as it forces Fediverse users to follow links to see the content, which is the opposite idea of the crossposter, which is to facilitate transition from twitter to the fediverse)
In this spirit, I'm not implementing this one. Sorry!
