### ISSUE TITLE
Crosspost Twitter mentions to Mastodon?

### ISSUE THREAD

**Issue by trwnh** [renatolond/mastodon-twitter-poster#66]
Maybe this is out of scope, but since you can already crosspost @user@twitter.com from Mastodon to Twitter, perhaps it wouldn't be too far out to also have a way to receive Twitter mentions in Mastodon? I would like to hear some feedback on this idea.

**Comment by renatolond** [comment]
Hi!
You mean posting @user@mastodon.domain and they get mentioned on Mastodon? This should already work, the only thing is that there's no option to turn it off (since if you just type it I have nothing to replace it with 😄)

**Comment by trwnh** [comment]
Ah, let me clarify:

Current behavior, as I understand it:
* Posting @user@twitter.com on Mastodon will link to a user once crossposted to Twitter.
* Posting @user@mastodon.domain on Twitter will link to a user once crossposted to Mastodon.

Proposed addition:
* Fetch Twitter API mentions somehow, and crosspost them to Mastodon, so that you can reply to them in Mastodon, and they will be crossposted back to Twitter

Since the crossposting is already handled very well by this tool, it seems very useful to crosspost not just statuses, but also mentions. But I understand if you feel this is out-of-scope, or that a separate mentions fetcher should be implemented as a different app entirely.

**Comment by renatolond** [comment]
Ah, okay, I think I got it now. So the idea is suppose that we have alice (as @alice) is on twitter and mastodon (as @alice@mastodon.domain), and Bob is on mastodon (as bob@mastodon.domain) as on twitter (@bob).

So if Alice posts on Twitter:
"Hey, @bob, check this out!"
It would get crossposted as
"Hey, @bob@mastodon.social, check this out!"

Is that it?

**Comment by trwnh** [comment]
That seems correct. The use case would be that Bob is primarily on Mastodon and doesn't want to keep checking Twitter mentions. I suppose it could also be added in reverse (fetch Mastodon mentions into a Twitter crossposter), but I'm more interested in the first one :)

**Comment by renatolond** [comment]
Hmm, well, the issue is that I can only do that between two users of the crossposter, if Bob gets a message from Carl on Twitter which is not using the crossposter (or even, not using Mastodon), there's no profile for me to post it on Mastodon.

Other than that, I don't know how to present the choice in a way that makes this useful. I would only feel comfortable to change the mention of the Alice if she checked an option to do so. And then I would only be comfortable to use Bob's information if he agreed to that. So I can imagine not a lot of people checking the box to make it useful.

I'm not against this one, but I don't know if in the end it would be useful for what you need 🤔

**Comment by trwnh** [comment]
So I guess it's out of scope, then? My idea was that since Bob authorized with both the Twitter and Mastodon APIs, then it would be easy to fetch mentions from the API, then post them to the other service.

For example, what I'm trying to do is something like this:

* I want to use Mastodon primarily, but still be able to communicate with Twitter users who mention me.
* I would set up a bridge or crossposter, so that when I type @user@twitter.com, a tweet would be sent from my connected Twitter account mentioning @user.
* What I am currently unable to do, but am requesting or trying to find, is to fetch my Twitter mentions and have them appear in Mastodon somehow. For example, if I were to receive a mention from @user on Twitter, my Mastodon account would receive a toot similar to "@user@twitter.com: @trwnh [message]". I could then reply to this toot and the mention would be converted as normal.

If this is too much for this project, then I understand. Hopefully I made it more clear what I am looking for. My thought was that since this app authenticates with both accounts and crossposts in both directions, it could maybe also fetch mentions as a bridge.

**Comment by renatolond** [comment]
Yeah, it's clear for me now :)

But there's some issues. For instance: if you direct message yourself on Mastodon, you don't get notified. Since direct messages are shown on your home timeline and not in a separate column, it means that you won't get notified and the message could possibly get lost down in the timeline if you were not checking mastodon at the time. So in this case it might be that you don't see mentions that you got on twitter.

Another issue is what happens when you're mentioned in a thread? You might not have seen previous messages and then you'll be left without a meaningful context. Which could be solved by adding a link to the original message, but then you'll be going back to Twitter anyway. (specially if the user that mentioned you has a locked account, which means you'll have to login to twitter to see the message)

A third issue has to do with #54, if other people are also mentioned, it might be that we pass the 500 char limit.

**Comment by trwnh** [comment]
Hmm, that all makes sense. I did some more testing with mentioning myself in toots, and you're correct, it doesn't notify me even though I am mentioned in the toot. This happens regardless of the toot's privacy, however. It seems Mastodon default behavior is to not notify you when you mention yourself. This means one of the following must occur:

a) Mastodon changes its behavior and starts showing you self-mentions
b) Cross-notifications are sent from a completely seperate / bot account on Mastodon, so that you get notified.

I don't think a) is a good idea for Mastodon to adopt, so that means that it would be best to pursue this kind of use case from a dedicated and separate relay account, which would be out of scope of this tool. I'm not sure how interested you or others may be in this kind of usage, but I will probably end up creating a relay account on botsin.space and have it mention me on Mastodon whenever I receive a Twitter mention.

To solve the issue of going over 500 characters in issue #54, it would probably only be necessary to show the person posting the tweet and their mention of you; all others can be collapsed into "@user mentioned you ...and n others". I find that the more common issue is in compacting a 500-character toot into a 280-character tweet, and I'm personally fine with it posting a link to Mastodon. But perhaps this kind of conversation is best conducted on issue #54 instead. :)
