### ISSUE TITLE
toots that are only an image do not crosspost to twitter

### ISSUE THREAD

**Issue by jahtnamas** [renatolond/mastodon-twitter-poster#679]
i have checked all the mastodon->twitter options to see if i had missed anything but it seems there isn't such an option.

when i post toots on the mastodon instance that i use (not own), i expect them to be crossposted to my twitter account. i tried several times yesterday to have twitter catch the toot i kept sending that was only an image. it finally worked when i added text to the toot.

i decided to queue three unthreaded toots to the crossposter: one text-only toot without an image, one just with an image, and one with an image and text. on twitter only two of those posts arrived: the text-only post, and the one with both image and text. [screenshots here.](https://queer.party/@jahtnamas/107963757364931188) (i hope you'll pardon my snarkiness here.)

i perused the issues forum for a similar issue but it seems to have never come up. is this a bug in the crossposting software or a configuration issue with my instance?

**Comment by a-dows** [comment]
Bumped—I have a bot on mastodon I want to crosspost to twitter that just posts images (with captions).

**Comment by renatolond** [comment]
I think this is a side effect of treatment for empty toots. I think pleroma in the past allowed completely empty posts (no picture, no body, no CW) and this would fail on twitter
I added a check but I don't check for the images, so I believe this is skipping posts with no body but with only an image. It's not intentional and it's indeed a bug
