### ISSUE TITLE
Include boost content

### ISSUE THREAD

**Issue by nevillepark** [renatolond/mastodon-twitter-poster#79]
Would it be possible to actually include the text of a boost when cross-posting it to Twitter? This would be especially helpful when a) the toot is short enough to fit in a tweet, or b) the boosted toot contains a link. Instead of 

> Boosted: https://instance.social/@user/1234567890/

you would see, for example,

> Boosted @user@instance.social: Big if true https://nytimes.com/2018/03/01/entertainment/half-life-3-announced.html
>
>  https://instance.social/@user/1234567890/

or 

> Boosted @user@instance.social: Jam (jean ham) 
>
>  https://instance.social/@user/1234567890/

Not sure how this would work with Open Graph, though.

**Comment by renatolond** [comment]
Hi, Neville!
Technically it's possible, but it's not like that by design. Not because of length, but to avoid content from users to "leak" to Twitter. There's a lot of users from Masto that left Twitter for privacy and harassing concerns and if they are not using the crossposter, there's no way to know if they would be okay with their content being posted over there. When we only post boosted + link, there's no content that's searchable on Twitter from the boost, so it's only seen by people that open the link or check out the open graph expansion.

**Comment by raimue** [comment]
Why is it okay to use the content from Twitter and show it on Mastodon, but not vice-versa? This is a double-standard you are applying. As far as I see, there is also no way for Twitter users to opt-out. By your argument content should not be reposted in any direction.

Please reconsider this decision. If we want to bring more people to Mastodon, it would be more helpful if boosts actually showed what people are missing out on instead of just a generic text and an URL nobody is going to click.

**Comment by renatolond** [comment]
Hi, Rainer!
Twitter and Mastodon have very different models, and that's why it's a very different treatment I give to the two. When you post publicly in Twitter, your post can be found by anyone else on Twitter, which is not the case on Mastodon and because of this expectations are different for the people posting in both.

I'm sorry, but I don't think I'll be changing my stance on this one.

**Comment by raimue** [comment]
I will accept any decision as you are maintaining this software and you are in charge of setting its policies. (A great piece of software and service by the way, thank you!)

We seem to disagree on who can find posts on mastodon. And as I see it, that is already anyone and not under your control if you post to a public timeline. By boosting, it can be shared with any other user on any other instance. So, jokingly, I see Twitter as another Mastodon instance that just has not adopted the protocol yet. 😉

Be aware that apps like Tootdon already implement [a search index for public timelines](https://mstdn.jp/@tootdon/99830170563103200). I am pretty sure this will not be the last app to do this. In fact, others may already collect all toots but do not tell you publicly about it. Telling users that toots cannot be found is a wrong expectation of privacy. The only way to keep somewhat more privacy is to share to followers-only, which also already disables the boost feature.

**Comment by nevillepark** [comment]
Thanks @renatolond, that is quite fair.

**Comment by schiessle** [comment]
> When you post publicly in Twitter, your post can be found by anyone else on Twitter, which is not the case on Mastodon and because of this expectations are different for the people posting in both.

Maybe I miss something, but I don't see how this is in any way different? Mastodon is a public network as well. Everyone can browser your profile, probably even use random search engine to find stuff you tooted.

I think it would be fine not to forward boosts to Twitter if they are part of a private message exchange (don't even know if it is possible to boost PM on Mastodon, never tried) or from a non-public profile. But If someone boost a public toot, I don't see how it protects the privacy in any way if you just forward the link instead of the content. If you fear that the user name is exposed along the content, then how about posting the content without the uid, just `Boosted: Hello World` optionally with a link to a toot. Then it would be as private and anonymous as just a link. If people would chose to forward boosts without a link you could even argue that it is more private and anonymous then the current behavior which exposes the whole public profile and all the toot's of a Mastodon user with just two clicks.

**Comment by renatolond** [comment]
My point is full-text search. When I post something public on mastodon, you can see it passing by on your local/federated timeline or by getting it boosted by someone in your home timeline. However, there's no [in-software] way to search for that toot.

Which is not the case for twitter. And that's why I don't think it's the same when posting in both directions. There might be ways of finding the messages using search engines some of the times, but I don't think it's fair to a user that has "do not be indexed by search engines" ticked on their profile to have their messages crossposted over to twitter.

When you post only the link, there's no full text search on the link.

**Comment by schiessle** [comment]
Thanks for explaining your point @renatolond 

> but I don't think it's fair to a user that has "do not be indexed by search engines" ticked on their profile to have their messages crossposted over to twitter.

What about all the other Mastodon, GNU Social, Friendica,... servers the toot gets forwarded? This settings only applies to your profile on your instance, right?

> When you post only the link, there's no full text search on the link.

Not within the public Twitter search, right. But on all other search engines who index Twitter and Twitter itself probably also follow links you post and use the data for their interests. Both bots and humans who follow the link will probably read more about you as if you would only forward "Boosted: Hello World" without a link if the text fits the Twitter char limit.

I still tend to think that positing only the link gives the users most of the time a false sense of privacy while at the same time making the feature way less useful. But at the end, it is of course your decision.

**Comment by renatolond** [comment]
> What about all the other Mastodon, GNU Social, Friendica,... servers the toot gets forwarded to? This settings only applies to your profile on your instance, right?
Kind of, at least in Mastodon, as far as I know, there's no public page for a profile that does not belong to the instance. So if you have your profile at instance X and your toot gets bosted to instance Y, only public link that could be seen for that is a local reply, I think.
When we talk about other fediverse softwares, I don't know how they behave.

In theory, a robots.txt-obeying search engine should not index even if it follows the link since the link (at least as mastodon boosts work) goes back to the original toot, which would be in the original instance and have the `<meta content='noindex' name='robots'>`. 

I understand that bad actors exist, however, since I cannot easily do an "opt-in of my content getting bosted over to twitter" for non-crossposter users, I would really rather simply not crosspost the full content. With the link anyone can go to the original toot (and some twitter clients even already expand the preview over there).

**Comment by mxmehl** [comment]
> I still tend to think that positing only the link gives the users most of the time a false sense of privacy while at the same time making the feature way less useful. But at the end, it is of course your decision.

I agree to this stand. From a perspective of a typical Twitter user, the current solution looks like "this Mastodon thingy" is broken software. It wouldn't attract me to become part of it. Basically no one clicks links without any useful information attached to it.

We could help make others interested in the Fediverse by showing the cool content posted there. The privacy argument, as Björn explained, doesn't make sense in the internet with the privacy-ignoring actors it contains, and the already existing Fediverse issues.
