### ISSUE TITLE
 Sorry, fosstodon.org is blocked in this instance. 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [renatolond/mastodon-twitter-poster#853]
trying to use your tool for crossposting to twitter :(

**Comment by renatolond** [comment]
Hey @AbhimanyuAryan, fosstodon is blocked in `masto.donte.com.br` and so it's also blocked in `crossposter.masto.donte.com.br`. You can look for another crossposter instance that allows for it or use a different tool.

**Comment by fredrikaverpil** [comment]
@renatolond hey, I just joined fosstodon.org as I'm a developer and therefore figured this was a fitting mastodon server choice. When I searched for a cross post service, I found your excellent project - but I was a bit surprised to see you have blocked fosstodon.org from it. Was there any specific reason for blocking fosstodon.org?

**Comment by AbhimanyuAryan** [comment]
@fredrikaverpil same question also looking for a reason which was not communicated. But then I found moa bridge which is pretty nice

**Comment by renatolond** [comment]
@fredrikaverpil The moderation team in `masto.donte.com.br` had moderation issues with fosstodon a few years ago and decided to block it, that's why. As a standard, I block instances which are blocked in `masto.donte.com.br` since it is also my main instance and the instance where the crossposter account is available on.
I'll lock this thread as this is an issue tracker for the tool and not for my instance specifically :)
