### ISSUE TITLE
Dead man's switch, to help with Twitter --> Mastodon self-marketing spam?

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#86]
Hello!

Gargron [said](https://github.com/tootsuite/mastodon/pull/7016#issuecomment-378093916):

>A lot of new people are using these Twitter to Mastodon cross-posters. But do we really want to encourage that? What it enables is "set and forget", where people set the cross-posting up and never visit Mastodon again. They won't respond to toots then. So it becomes fake activity, and waste of disk space and processing power, and spam on the public timelines.
>
>Tumblr doesn't allow cross-posting from Twitter, only to, and the same was true for Postereus and other richer platforms. Cross-posting is marketing, and I now realize more than ever that Twitter to Mastodon cross-posting is hurting Mastodon.

I'm wondering if a dead man's switch is possible? If someone doesn't post on Mastodon for x days, the Twitter --> Mastodon part of the crossposter stops working?

It somewhat help with the issue of people setting up a crossposter and then logging out of Mastodon and forgetting about it, being unable to see or respond to replies on Mastodon, etc.

And it might also help the crossposter, by weeding out all the people who set it up ages ago and forgot about it, and would probably take it down if they were more conscientious.

**Comment by renatolond** [comment]
Hmm, I have some troubles with this, there's some bots in bots-in.space and similar that use the crossposter, and sometimes they only do post in twitter and bring their posts over and they would be caught by this. (And they do not post only RTs ou anything that would be distinguishable from a normal post in Masto, except for the source of it)

I'm willing to try and find a way to make this configurable by instances admins so that each instance can set their own rules around this, I'd have to think on how to do it though, to guarantee that only admins can access this configuration.

It greatly depends on instance size, but personally I try to talk to users in masto.donte that are being "crossposting-bots" to either install an app or add email notifications so that they can be aware that someone interacted with them over the crossposter.
Since a crossposter is considered an "app", Mastodon does not consider a user as inactive if they are only crossposting things, so users never get the "while you were away" email or anything of the likes.

In any case, I'll think about a way to have this per-instance.

**Comment by Cassolotl** [comment]
>Since a crossposter is considered an "app", Mastodon does not consider a user as inactive if they are only crossposting things, so users never get the "while you were away" email or anything of the likes.

Ahhhh good point. Ack.

>there's some bots in bots-in.space and similar that use the crossposter, and sometimes they only do post in twitter and bring their posts over and they would be caught by this. (And they do not post only RTs ou anything that would be distinguishable from a normal post in Masto, except for the source of it)

Yes, that is a problem! :/ Maybe it could be a setting, like, "stop crossposting if I am not active on Mastodon for x days", that is on by default - and bot owners can turn it off manually? And then most people would ignore it, hopefully? Or at least *some* people would ignore it!

**Comment by foozmeat** [comment]
Hi, this raises some interesting questions. When I built moa.social my motivation was to make it easier for people on twitter to experience conversations on mastodon. I also thought that bringing over "high-profile" twitter users would help adoption. I understand the counter-argument but I feel slightly ruffled by gargron dictating what is and isn't good for the network.

Something I would consider implementing in Moa is that you have to re-save your prefs every 30? days or your cross-posting is disabled. Moa can send a DM to the mastodon account that's linked and that should indicate whether the person is still "participating".

Can instance admins ban a particular app from their server? That seems like a good tool as well? I would be happy to make it easier for an admin to prevent Moa from being used. I wonder if the app callback URL is enough?

**Comment by renatolond** [comment]
The 30 days re-saving could be interesting, but also gets back to the "users using apps do not get notifications" issue (sending a DM to masto account could be useless in this case and only DM to twitter account would work). I would really like that this would not be the case, since it would naturally get users to come back to Mastodon.

Combining with your idea, if there was an easy way for admins to configure how many days until the dead man switch is activated we could send DMs to users in Mastodon letting they know their crossposter would be disabled in XX hours due to instance rules or something of the like.

In the discussion @Cassolotl started I also saw someone saying that would rather that the privacy level of the toots would be more restrict instead of stop posting altogether, which could also be nice.

**Comment by Cassolotl** [comment]
I feel like as an active person in both places I like that my crossposted Twitter --> Mastodon toots are public - I feel like that's okay, my crossposted toots aren't bothering anyone, I think? But if the privacy level was bumped down to unlisted after x days of not logging into Mastodon (or not responding to a DM confirming that you'd like crossposting to continue), that would be a nice compromise? And then maybe after y days crossposting could stop altogether?
