### ISSUE TITLE
sidekiq has two queues but docker-compose only mentions one

### ISSUE THREAD

**Issue by coro1404** [renatolond/mastodon-twitter-poster#876]
Hi - at least in my installation the crossposter comes up with two queues in sidekiq. One is named default and seems to be only for the housekeeping jobs and one is name "high" which contains the actual crossposting jobs. 

I modified the docker-compose.yml for crossposter-sidekiq like this

[...]
`command: bundle exec sidekiq -c 5 -q high -q default`

I was wondering why the queue was added and why this is not reflected in the docker-compose.yml. 

Will provide a PR if necessary

**Comment by renatolond** [comment]
Also, high is only used to fill `default` with the crossposting jobs, to clarify

**Comment by us3r1d** [comment]
I am so glad I finally ran into this report; I just installed the crossposter yesterday, got the web interface running this morning (note: it can't run from a home directory without nginx having perms to read that directory :) and have been banging my head on why no statuses were moving since then.

This has not been a very easy install.  :-)

But, it's up and running and thats' what matters; thanks.

**Comment by coro1404** [comment]
> Hey, sorry, I added this queue very recently: https://github.com/renatolond/mastodon-twitter-poster/blob/main/CHANGELOG.md?plain=1#L3 Forgot about the docker stuff because I personally don't use it, if you have the time a PR would be greatly appreciated :)

PR done
