### ISSUE TITLE
Crossposts to Twitter have links to other instances broken

### ISSUE THREAD

**Issue by richlv** [renatolond/mastodon-twitter-poster#922]
Example:
https://mastodon.social/@richlv/109596454576141985
https://twitter.com/RihardsOlups/status/1608408257684557824

Notice how
https://mastodon.social/@overholt@glammr.us/109587412485871313
got transformed into
[mastodon.social](https://t.co/ujy8cuE5kz)🐘overholt@glammr.us/109587412485871313

**Comment by CallMeTarush** [comment]
Hi @renatolond Seems the issue seems to be coming up from [here](https://github.com/renatolond/mastodon-twitter-poster/blob/main/app/objects/toot_transformer.rb#L43)

Could you tell me what the purpose of this was exactly when put in? I am assuming its translating something unicode into an emoji? Unsure.

**Comment by richlv** [comment]
Yay, thank you for the fix :)
